### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by andersy005** [intake/intake-esm#277]
The following new/existing features could use some detailed examples in the documentation 

- [ ] Disabling aggregations with `to_dataset_dict(aggregate=False)`, and via the `groupby_attrs=[]` attribute
- [ ] How to use regular expressions + wildcard expressions in `search()`. E.g.: https://github.com/intake/intake-esm/issues/266#issuecomment-670984331. Jeff has a great example about this: https://nbviewer.jupyter.org/github/NCAR/cesm-lens-aws/blob/master/notebooks/EnhancedIntakeCatalogDemo.ipynb
- [ ] Manipulating the dataframe. E.g.: https://github.com/intake/intake-esm/issues/266#issuecomment-671468165, 
- [x] Update the `cdf_kwargs` and `zarr_kwargs` information in the `to_dataset_dict()` docstring to inform the user on how these arguments are used in regards to chunking. See this issue: https://github.com/intake/intake-esm/issues/156

Create notebooks for the first three bullet points and put them in the `docs/source/notebooks` directory.

**Comment by jukent** [comment]
Hi @andersy005 @bonnland when I try to run cells from Jeff's notebook (https://nbviewer.jupyter.org/github/NCAR/cesm-lens-aws/blob/master/notebooks/EnhancedIntakeCatalogDemo.ipynb) I am unable to read in the original collection file.

```
# Open original collection description file
cat_url_orig = 'https://ncar-cesm-lens.s3-us-west-2.amazonaws.com/catalogs/aws-cesm1-le.json'
coll_orig = intake.open_esm_datastore(cat_url_orig)
```

returns
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-67f3a099374b> in <module>
      1 # Open original collection description file
      2 cat_url_orig = 'https://ncar-cesm-lens.s3-us-west-2.amazonaws.com/catalogs/aws-cesm1-le.json'
----> 3 coll_orig = intake.open_esm_datastore(cat_url_orig)

TypeError: 'NoneType' object is not callable
```

Do you have any insight on why this is?

**Comment by andersy005** [comment]
@jukent, I recommend using the master branch of `intake-esm`. The latest release had a bug (though It doesn't appear to be related to the issue you are running into) in it and I fixed it in https://github.com/intake/intake-esm/commit/4ffd85eed14b84e2f10af4ba26ebcc67c379371c. 


```bash
python -m pip install git+https://github.com/intake/intake-esm.git@master
```


Once you've installed from the master branch and you keep running into this issue, run the following and post the output here

```python
from intake_esm import show_versions
show_versions()
```

**Comment by jukent** [comment]
@andersy005 It is working now! Thank you. Curious, if you don't suspect it is related to that bug.

Here is the output:

```
INSTALLED VERSIONS
------------------

cftime: 1.2.1
dask: 2.26.0
fastprogress: 0.2.7
fsspec: 0.8.2
gcsfs: 0.7.1
intake: 0.6.0
intake_esm: 2020.8.15.post6
netCDF4: 1.5.4
pandas: 1.1.2
requests: 2.24.0
s3fs: 0.5.1
xarray: 0.16.0
zarr: 2.4.0
```

**Comment by andersy005** [comment]
Awesome :). 

I think I figured out the culprit. It appears that the error is due to `intake-esm` missing from the environment you were using.... I tested it by creating a new environment and installing intake only. 


```python
In [1]: import intake

In [2]: cat_url_orig = 'https://ncar-cesm-lens.s3-us-west-2.amazonaws.com/catalogs/aws-cesm1-l
   ...: e.json'

In [3]: coll_orig = intake.open_esm_datastore(cat_url_orig)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-c41fd2dc7bac> in <module>
----> 1 coll_orig = intake.open_esm_datastore(cat_url_orig)

TypeError: 'NoneType' object is not callable
```

- Confirm that intake-esm is not installed:

```
In [4]: import intake_esm
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-1e5adfe3497f> in <module>
----> 1 import intake_esm

ModuleNotFoundError: No module named 'intake_esm'
```

**Comment by zentouro** [comment]
Hi @andersy005, I seem to be experiencing the same issue, except installing the master branch of `intake-esm` didn't seem to fix my issue. 

Here's the code and error: 

`cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
col = intake.open_esm_datastore(cat_url)
col`

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-8ecbe93f2ef5> in <module>
      1 cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
----> 2 col = intake.open_esm_datastore(cat_url)
      3 col

TypeError: 'NoneType' object is not callable`

**Comment by andersy005** [comment]
@zentouro, thank you for the minimal example... For some reason, I am unable to reproduce the issue

```python
In [1]: import intake

In [2]: import intake_esm

In [3]: intake_esm.show_versions()

INSTALLED VERSIONS
------------------

cftime: 1.2.1
dask: 2.28.0
fastprogress: 0.2.7
fsspec: 0.8.3
gcsfs: None
intake: 0.6.0
intake_esm: 2020.8.15.post6
netCDF4: 1.5.4
pandas: 1.1.2
requests: 2.24.0
s3fs: 0.5.1
xarray: 0.16.1
zarr: 2.4.0

In [4]: cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
   ...: col = intake.open_esm_datastore(cat_url)
/Users/abanihi/opt/miniconda3/envs/playground/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3417: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]: col.df.head()
Out[5]:
  activity_id institution_id  ... dcpp_init_year   version
0  AerChemMIP        AS-RCEC  ...            NaN  20200310
1  AerChemMIP            BCC  ...            NaN  20190718
2  AerChemMIP            BCC  ...            NaN  20191127
3  AerChemMIP            BCC  ...            NaN  20190809
4  AerChemMIP            BCC  ...            NaN  20191127
```


What is the output of `dict(intake.registry)`???


```python
In [9]: dict(intake.registry)
Out[9]:
{'yaml_file_cat': intake.catalog.local.YAMLFileCatalog,
 'yaml_files_cat': intake.catalog.local.YAMLFilesCatalog,
 'esm_datastore': intake_esm.core.esm_datastore,
 'esm_group': intake_esm.source.ESMGroupDataSource,
 'esm_single_source': intake_esm.source.ESMDataSource,
 'catalog': intake.catalog.base.Catalog,
 'csv': intake.source.csv.CSVSource,
 'intake_remote': intake.catalog.base.RemoteCatalog,
 'ndzarr': intake.source.zarr.ZarrArraySource,
 'numpy': intake.source.npy.NPySource,
 'textfiles': intake.source.textfiles.TextFilesSource,
 'zarr_cat': intake.catalog.zarr.ZarrGroupCatalog}

**Comment by zentouro** [comment]
Hi @andersy005 

here's what ` dict(intake.registry)` returns 

```
{'yaml_file_cat': intake.catalog.local.YAMLFileCatalog,
 'yaml_files_cat': intake.catalog.local.YAMLFilesCatalog,
 'esm_datastore': intake_esm.core.esm_datastore,
 'esm_group': intake_esm.source.ESMGroupDataSource,
 'esm_single_source': intake_esm.source.ESMDataSource,
 'catalog': intake.catalog.base.Catalog,
 'csv': intake.source.csv.CSVSource,
 'intake_remote': intake.catalog.base.RemoteCatalog,
 'ndzarr': intake.source.zarr.ZarrArraySource,
 'numpy': intake.source.npy.NPySource,
 'textfiles': intake.source.textfiles.TextFilesSource,
 'zarr_cat': intake.catalog.zarr.ZarrGroupCatalog}
```

**Comment by andersy005** [comment]
Okay.. That looks sane :) Are you running this locally (on your laptop) or in the cloud? I am asking because I'd to see if I can try diagnosing the issue while using the same environment as you.

**Comment by zentouro** [comment]
I'm running it locally in jupyter notebook in a miniconda environment.

I'm also quite new to this, so I could be messing something up.

**Comment by andersy005** [comment]
@zentouro, No worries... Can you try the following:


```python
In [1]: import intake_esm

In [2]: cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"

In [3]: col = intake_esm.core.esm_datastore(cat_url)
```

and see if it works?

**Comment by zentouro** [comment]
yup that works!

**Comment by andersy005** [comment]
That's both good news and weird :) 

According to this:

> here's what ` dict(intake.registry)` returns
> 
> ```
> {'yaml_file_cat': intake.catalog.local.YAMLFileCatalog,
>  'yaml_files_cat': intake.catalog.local.YAMLFilesCatalog,
>  'esm_datastore': intake_esm.core.esm_datastore,
>  'esm_group': intake_esm.source.ESMGroupDataSource,
>  'esm_single_source': intake_esm.source.ESMDataSource,
>  'catalog': intake.catalog.base.Catalog,
>  'csv': intake.source.csv.CSVSource,
>  'intake_remote': intake.catalog.base.RemoteCatalog,
>  'ndzarr': intake.source.zarr.ZarrArraySource,
>  'numpy': intake.source.npy.NPySource,
>  'textfiles': intake.source.textfiles.TextFilesSource,
>  'zarr_cat': intake.catalog.zarr.ZarrGroupCatalog}
> ```

Calling `intake.open_esm_datastore(cat_url)` should work as expected, but it appears that some funny business is happening inside intake... When you get a chance, could you try creating a new test environment (assuming you are using conda) via 

```bash
$ conda env create -n intake-test -c conda-forge intake-esm ipython
$ conda activate intake-test
$ ipython
```

and then run 

```python
import intake
cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
col = intake.open_esm_datastore(cat_url)
```

?

**Comment by zentouro** [comment]
Okay, tried doing that and received this error: 

```
In [2]: import intake                                                           
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-924f1ec0a922> in <module>
----> 1 import intake

ModuleNotFoundError: No module named 'intake'
```

**Comment by andersy005** [comment]
Oooh.. it looks like `intake` is not installed in that environment... Assuming you have `intake-test` environment activated, install intake via `conda install -c conda-forge intake`, and try running the intake import again.

**Comment by zentouro** [comment]
Frustratingly, when I try to install `intake` it says: `# All requested packages already installed.`
